import java.util.HashMap;

public class CountryCurrencyMapper {
    public static String getCurrencyCode(String countryName) {
        return nameToCurrency.getOrDefault(countryName, "unknown");
    }

    private static final HashMap<String, String> nameToCurrency;
    static {
        nameToCurrency = new HashMap<>();
        nameToCurrency.put("Andorra", "EUR");
        nameToCurrency.put("United Arab Emirates", "AED");
        nameToCurrency.put("Afghanistan", "AFN");
        nameToCurrency.put("Antigua and Barbuda", "XCD");
        nameToCurrency.put("Anguilla", "XCD");
        nameToCurrency.put("Albania", "ALL");
        nameToCurrency.put("Armenia", "AMD");
        nameToCurrency.put("Angola", "AOA");
        nameToCurrency.put("Argentina", "ARS");
        nameToCurrency.put("American Samoa", "USD");
        nameToCurrency.put("Austria", "EUR");
        nameToCurrency.put("Australia", "AUD");
        nameToCurrency.put("Aruba", "AWG");
        nameToCurrency.put("Azerbaijan", "AZN");
        nameToCurrency.put("Bosnia and Herzegovina", "BAM");
        nameToCurrency.put("Barbados", "BBD");
        nameToCurrency.put("Bangladesh", "BDT");
        nameToCurrency.put("Belgium", "EUR");
        nameToCurrency.put("Burkina Faso", "XOF");
        nameToCurrency.put("Bulgaria", "BGN");
        nameToCurrency.put("Bahrain", "BHD");
        nameToCurrency.put("Burundi", "BIF");
        nameToCurrency.put("Benin", "XOF");
        nameToCurrency.put("Saint Barthélemy", "EUR");
        nameToCurrency.put("Bermuda", "BMD");
        nameToCurrency.put("Brunei", "BND");
        nameToCurrency.put("Bolivia", "BOB");
        nameToCurrency.put("Brazil", "BRL");
        nameToCurrency.put("Bahamas", "BSD");
        nameToCurrency.put("Bhutan", "BTN");
        nameToCurrency.put("Botswana", "BWP");
        nameToCurrency.put("Belarus", "BYN");
        nameToCurrency.put("Belize", "BZD");
        nameToCurrency.put("Canada", "CAD");
        nameToCurrency.put("Cocos Islands", "AUD");
        nameToCurrency.put("Democratic Republic of the Congo", "CDF");
        nameToCurrency.put("Central African Republic", "XAF");
        nameToCurrency.put("Republic of the Congo", "XAF");
        nameToCurrency.put("Switzerland", "CHF");
        nameToCurrency.put("Ivory Coast", "XOF");
        nameToCurrency.put("Cook Islands", "NZD");
        nameToCurrency.put("Chile", "CLP");
        nameToCurrency.put("Cameroon", "XAF");
        nameToCurrency.put("China", "CNY");
        nameToCurrency.put("Colombia", "COP");
        nameToCurrency.put("Costa Rica", "CRC");
        nameToCurrency.put("Cuba", "CUP");
        nameToCurrency.put("Cape Verde", "CVE");
        nameToCurrency.put("Christmas Island", "AUD");
        nameToCurrency.put("Cyprus", "EUR");
        nameToCurrency.put("Czech Republic", "CZK");
        nameToCurrency.put("Germany", "EUR");
        nameToCurrency.put("Djibouti", "DJF");
        nameToCurrency.put("Denmark", "DKK");
        nameToCurrency.put("Dominica", "XCD");
        nameToCurrency.put("Dominican Republic", "DOP");
        nameToCurrency.put("Algeria", "DZD");
        nameToCurrency.put("Ecuador", "USD");
        nameToCurrency.put("Estonia", "EUR");
        nameToCurrency.put("Egypt", "EGP");
        nameToCurrency.put("Western Sahara", "MAD");
        nameToCurrency.put("Eritrea", "ERN");
        nameToCurrency.put("Spain", "EUR");
        nameToCurrency.put("Ethiopia", "ETB");
        nameToCurrency.put("Finland", "EUR");
        nameToCurrency.put("Fiji", "FJD");
        nameToCurrency.put("Falkland Islands", "FKP");
        nameToCurrency.put("Micronesia", "USD");
        nameToCurrency.put("Faroe Islands", "DKK");
        nameToCurrency.put("France", "EUR");
        nameToCurrency.put("Gabon", "XAF");
        nameToCurrency.put("United Kingdom", "GBP");
        nameToCurrency.put("Grenada", "XCD");
        nameToCurrency.put("Georgia", "GEL");
        nameToCurrency.put("French Guiana", "EUR");
        nameToCurrency.put("Guernsey", "GGP");
        nameToCurrency.put("Ghana", "GHS");
        nameToCurrency.put("Gibraltar", "GIP");
        nameToCurrency.put("Greenland", "DKK");
        nameToCurrency.put("Gambia", "GMD");
        nameToCurrency.put("Guinea", "GNF");
        nameToCurrency.put("Guadeloupe", "EUR");
        nameToCurrency.put("Equatorial Guinea", "XAF");
        nameToCurrency.put("Greece", "EUR");
        nameToCurrency.put("South Georgia and the South Sandwich Islands", "GBP");
        nameToCurrency.put("Guatemala", "GTQ");
        nameToCurrency.put("Guam", "USD");
        nameToCurrency.put("Guinea-Bissau", "XOF");
        nameToCurrency.put("Guyana", "GYD");
        nameToCurrency.put("Hong Kong", "HKD");
        nameToCurrency.put("Honduras", "HNL");
        nameToCurrency.put("Croatia", "EUR");
        nameToCurrency.put("Haiti", "HTG");
        nameToCurrency.put("Hungary", "HUF");
        nameToCurrency.put("Indonesia", "IDR");
        nameToCurrency.put("Ireland", "EUR");
        nameToCurrency.put("Israel", "ILS");
        nameToCurrency.put("Isle of Man", "IMP");
        nameToCurrency.put("India", "INR");
        nameToCurrency.put("Iraq", "IQD");
        nameToCurrency.put("Iran", "IRR");
        nameToCurrency.put("Iceland", "ISK");
        nameToCurrency.put("Italy", "EUR");
        nameToCurrency.put("Jersey", "JEP");
        nameToCurrency.put("Jamaica", "JMD");
        nameToCurrency.put("Jordan", "JOD");
        nameToCurrency.put("Japan", "JPY");
        nameToCurrency.put("Kenya", "KES");
        nameToCurrency.put("Kyrgyzstan", "KGS");
        nameToCurrency.put("Cambodia", "KHR");
        nameToCurrency.put("Kiribati", "AUD");
        nameToCurrency.put("Comoros", "KMF");
        nameToCurrency.put("Saint Kitts and Nevis", "XCD");
        nameToCurrency.put("North Korea", "KPW");
        nameToCurrency.put("South Korea", "KRW");
        nameToCurrency.put("Kuwait", "KWD");
        nameToCurrency.put("Cayman Islands", "KYD");
        nameToCurrency.put("Kazakhstan", "KZT");
        nameToCurrency.put("Laos", "LAK");
        nameToCurrency.put("Lebanon", "LBP");
        nameToCurrency.put("Saint Lucia", "XCD");
        nameToCurrency.put("Liechtenstein", "CHF");
        nameToCurrency.put("Sri Lanka", "LKR");
        nameToCurrency.put("Liberia", "LRD");
        nameToCurrency.put("Lesotho", "LSL");
        nameToCurrency.put("Lithuania", "EUR");
        nameToCurrency.put("Luxembourg", "EUR");
        nameToCurrency.put("Latvia", "EUR");
        nameToCurrency.put("Libya", "LYD");
        nameToCurrency.put("Morocco", "MAD");
        nameToCurrency.put("Monaco", "EUR");
        nameToCurrency.put("Moldova", "MDL");
        nameToCurrency.put("Montenegro", "EUR");
        nameToCurrency.put("Saint Martin", "EUR");
        nameToCurrency.put("Madagascar", "MGA");
        nameToCurrency.put("Marshall Islands", "USD");
        nameToCurrency.put("Macedonia", "MKD");
        nameToCurrency.put("Mali", "XOF");
        nameToCurrency.put("Myanmar", "MMK");
        nameToCurrency.put("Mongolia", "MNT");
        nameToCurrency.put("Macao", "MOP");
        nameToCurrency.put("Northern Mariana Islands", "USD");
        nameToCurrency.put("Martinique", "EUR");
        nameToCurrency.put("Mauritania", "MRU");
        nameToCurrency.put("Montserrat", "XCD");
        nameToCurrency.put("Malta", "EUR");
        nameToCurrency.put("Mauritius", "MUR");
        nameToCurrency.put("Maldives", "MVR");
        nameToCurrency.put("Malawi", "MWK");
        nameToCurrency.put("Mexico", "MXN");
        nameToCurrency.put("Malaysia", "MYR");
        nameToCurrency.put("Mozambique", "MZN");
        nameToCurrency.put("Namibia", "NAD");
        nameToCurrency.put("New Caledonia", "XPF");
        nameToCurrency.put("Niger", "XOF");
        nameToCurrency.put("Norfolk Island", "AUD");
        nameToCurrency.put("Nigeria", "NGN");
        nameToCurrency.put("Nicaragua", "NIO");
        nameToCurrency.put("Netherlands", "EUR");
        nameToCurrency.put("Norway", "NOK");
        nameToCurrency.put("Nepal", "NPR");
        nameToCurrency.put("Niue", "NZD");
        nameToCurrency.put("New Zealand", "NZD");
        nameToCurrency.put("Oman", "OMR");
        nameToCurrency.put("Panama", "PAB");
        nameToCurrency.put("Peru", "PEN");
        nameToCurrency.put("French Polynesia", "XPF");
        nameToCurrency.put("Papua New Guinea", "PGK");
        nameToCurrency.put("Philippines", "PHP");
        nameToCurrency.put("Pakistan", "PKR");
        nameToCurrency.put("Poland", "PLN");
        nameToCurrency.put("Saint Pierre and Miquelon", "EUR");
        nameToCurrency.put("Pitcairn", "NZD");
        nameToCurrency.put("Puerto Rico", "USD");
        nameToCurrency.put("Palestinian Territory", "ILS");
        nameToCurrency.put("Portugal", "EUR");
        nameToCurrency.put("Palau", "USD");
        nameToCurrency.put("Paraguay", "PYG");
        nameToCurrency.put("Qatar", "QAR");
        nameToCurrency.put("Reunion", "EUR");
        nameToCurrency.put("Romania", "RON");
        nameToCurrency.put("Serbia", "RSD");
        nameToCurrency.put("Russia", "RUB");
        nameToCurrency.put("Rwanda", "RWF");
        nameToCurrency.put("Saudi Arabia", "SAR");
        nameToCurrency.put("Solomon Islands", "SBD");
        nameToCurrency.put("Seychelles", "SCR");
        nameToCurrency.put("Sudan", "SDG");
        nameToCurrency.put("Sweden", "SEK");
        nameToCurrency.put("Singapore", "SGD");
        nameToCurrency.put("Saint Helena", "SHP");
        nameToCurrency.put("Slovenia", "EUR");
        nameToCurrency.put("Svalbard and Jan Mayen", "NOK");
        nameToCurrency.put("Slovakia", "EUR");
        nameToCurrency.put("Sierra Leone", "SLE");
        nameToCurrency.put("San Marino", "EUR");
        nameToCurrency.put("Senegal", "XOF");
        nameToCurrency.put("Somalia", "SOS");
        nameToCurrency.put("Suriname", "SRD");
        nameToCurrency.put("South Sudan", "SDG");
        nameToCurrency.put("Sao Tome and Principe", "STD");
        nameToCurrency.put("El Salvador", "USD");
        nameToCurrency.put("Syria", "SYP");
        nameToCurrency.put("Swaziland", "SZL");
        nameToCurrency.put("Turks and Caicos Islands", "USD");
        nameToCurrency.put("Chad", "XAF");
        nameToCurrency.put("Togo", "XOF");
        nameToCurrency.put("Thailand", "THB");
        nameToCurrency.put("Tajikistan", "TJS");
        nameToCurrency.put("East Timor", "USD");
        nameToCurrency.put("Turkmenistan", "TMT");
        nameToCurrency.put("Tunisia", "TND");
        nameToCurrency.put("Tonga", "TOP");
        nameToCurrency.put("Turkey", "TRY");
        nameToCurrency.put("Trinidad and Tobago", "TTD");
        nameToCurrency.put("Tuvalu", "AUD");
        nameToCurrency.put("Taiwan", "TWD");
        nameToCurrency.put("Tanzania", "TZS");
        nameToCurrency.put("Ukraine", "UAH");
        nameToCurrency.put("Uganda", "UGX");
        nameToCurrency.put("United States", "USD");
        nameToCurrency.put("Uruguay", "UYU");
        nameToCurrency.put("Uzbekistan", "UZS");
        nameToCurrency.put("Vatican", "EUR");
        nameToCurrency.put("Saint Vincent and the Grenadines", "XCD");
        nameToCurrency.put("Venezuela", "VES");
        nameToCurrency.put("British Virgin Islands", "USD");
        nameToCurrency.put("U.S. Virgin Islands", "USD");
        nameToCurrency.put("Vietnam", "VND");
        nameToCurrency.put("Vanuatu", "VUV");
        nameToCurrency.put("Wallis and Futuna", "XPF");
        nameToCurrency.put("Samoa", "WST");
        nameToCurrency.put("Kosovo", "EUR");
        nameToCurrency.put("Yemen", "YER");
        nameToCurrency.put("Mayotte", "EUR");
        nameToCurrency.put("South Africa", "ZAR");
        nameToCurrency.put("Zambia", "ZMW");
        nameToCurrency.put("Zimbabwe", "ZWL");
    }
}